package com.example.electrodecutcompare;
import android.graphics.*; import java.util.*;
public final class DiagnosticAnalyzer{
 public static class Result{public Bitmap chart;public String summary;Result(Bitmap b,String s){chart=b;summary=s;}}
 public static Result analyze(HighSpeedAnalyzer.Result a,HighSpeedAnalyzer.Result b,AdvancedMotionAnalyzer.Result adv,RoiQualityAnalyzer.Metrics rb,GoldenBaselineStore.Baseline g,float mmPerPx,String pf){
  int n=Math.min(a.m.length,b.m.length);float ma=max(a.m),mb=max(b.m);ArrayList<Integer> ids=new ArrayList<>();for(int i=0;i<n;i++)ids.add(i);Collections.sort(ids,(x,y)->Float.compare(diff(a,b,y,ma,mb),diff(a,b,x,ma,mb)));
  ArrayList<Integer> top=new ArrayList<>();for(int id:ids){boolean far=true;for(int q:top)if(Math.abs(q-id)<4)far=false;if(far)top.add(id);if(top.size()==3)break;}
  String level=adv.score<18?"정상 후보":adv.score<35?"WATCH": "이상 후보";StringBuilder s=new StringBuilder();s.append("v0.7 Smart Diagnostic · ").append(pf).append(" · ").append(level).append("\n");
  s.append(String.format(Locale.getDefault(),"Motion Risk %.1f/100 · Top3 이상 순간",adv.score));for(int i=0;i<top.size();i++){int k=top.get(i);s.append(String.format(Locale.getDefault(),"\n#%d A %.3fs / B %.3fs · 편차 %.1f%%",i+1,a.t[Math.min(k,a.t.length-1)]/1000f,b.t[Math.min(k,b.t.length-1)]/1000f,diff(a,b,k,ma,mb)*100));}
  if(rb!=null){s.append(String.format(Locale.getDefault(),"\nNip Offset %.2f px",rb.nipOffsetPx));if(mmPerPx>0)s.append(String.format(Locale.getDefault()," ≈ %.3f mm",rb.nipOffsetPx*mmPerPx));s.append(String.format(Locale.getDefault()," · Tip Jitter %.2f px",rb.tipJitterPx));}
  if(g==null)s.append("\nGolden: 미등록 · 정상 영상을 확인한 뒤 '현재 결과 Golden 등록'을 사용하세요.");else{s.append(String.format(Locale.getDefault(),"\nGolden 대비 Motion Risk 변화 %+,.1f",adv.score-g.risk));if(rb!=null&&g.hasRoi)s.append(String.format(Locale.getDefault()," · Offset 변화 %+,.2fpx · Tip Jitter 변화 %+,.2fpx",rb.nipOffsetPx-g.offset,rb.tipJitterPx-g.tip));}
  s.append("\n판정 근거: Event 패턴 + Multi-Cycle/Jerk + ROI + Golden을 함께 사용합니다. NG 확정은 검증된 불량 기준 확보 후 적용합니다.");
  return new Result(draw(a,b,top,adv.score,g,pf),s.toString());
 }
 private static float diff(HighSpeedAnalyzer.Result a,HighSpeedAnalyzer.Result b,int i,float ma,float mb){if(i>=a.m.length||i>=b.m.length)return 0;return Math.abs(a.m[i]/ma-b.m[i]/mb);}private static float max(float[]v){float m=.001f;for(float x:v)m=Math.max(m,x);return m;}
 private static Bitmap draw(HighSpeedAnalyzer.Result a,HighSpeedAnalyzer.Result b,List<Integer> top,float risk,GoldenBaselineStore.Baseline g,String pf){int w=1200,h=760,l=70,r=1130,t=155,bot=535;Bitmap o=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(o);c.drawColor(Color.WHITE);Paint p=new Paint(1);p.setColor(Color.rgb(15,48,88));p.setTextSize(36);p.setFakeBoldText(true);c.drawText(LanguageManager.ts("v0.7 Smart Diagnostic / Top3 Anomaly"),45,55,p);p.setFakeBoldText(false);p.setTextSize(22);p.setColor(Color.DKGRAY);c.drawText(pf+" · Event deviation + Golden baseline",45,92,p);p.setStyle(Paint.Style.STROKE);p.setColor(Color.LTGRAY);c.drawRect(l,t,r,bot,p);float ma=max(a.m),mb=max(b.m);int n=Math.min(a.m.length,b.m.length);Paint pa=new Paint(1);pa.setStyle(Paint.Style.STROKE);pa.setStrokeWidth(4);pa.setColor(Color.rgb(30,90,210));Paint pb=new Paint(pa);pb.setColor(Color.rgb(220,65,45));for(int i=1;i<n;i++){float x1=l+(r-l)*(i-1f)/(n-1),x2=l+(r-l)*i/(n-1);c.drawLine(x1,bot-(bot-t-20)*a.m[i-1]/ma,x2,bot-(bot-t-20)*a.m[i]/ma,pa);c.drawLine(x1,bot-(bot-t-20)*b.m[i-1]/mb,x2,bot-(bot-t-20)*b.m[i]/mb,pb);}Paint mark=new Paint(1);mark.setColor(Color.MAGENTA);mark.setStrokeWidth(5);for(int j=0;j<top.size();j++){float x=l+(r-l)*top.get(j)/(float)Math.max(1,n-1);c.drawLine(x,t,x,bot,mark);p.setStyle(Paint.Style.FILL);p.setColor(Color.MAGENTA);p.setTextSize(22);c.drawText("#"+(j+1),x+5,t+28+25*j,p);}p.setColor(Color.DKGRAY);p.setTextSize(25);c.drawText(String.format(Locale.getDefault(),"Motion Risk %.1f/100 · Golden %s",risk,g==null?LanguageManager.ts("미등록"):String.format(Locale.getDefault(),"%.1f",g.risk)),70,600,p);p.setTextSize(21);c.drawText(LanguageManager.ts("파랑=A / 빨강=B / 자홍=Top3 이상 후보 순간"),70,642,p);c.drawText(LanguageManager.ts("※ 30fps 영상은 매우 짧은 충격을 놓칠 수 있어 고속촬영일수록 신뢰도가 높아집니다."),70,690,p);return o;}
}
