package com.example.electrodecutcompare;
import android.content.Context; import android.graphics.*; import android.media.MediaMetadataRetriever; import android.net.Uri; import java.util.Locale;
public final class HighSpeedAnalyzer {
 public static class Result { public float[] m; public long[] t; public int fps,event; Result(float[]m,long[]t,int f,int e){this.m=m;this.t=t;fps=f;event=e;} }
 public static class CompareResult { public Bitmap chart; public String summary; CompareResult(Bitmap b,String s){chart=b;summary=s;} }
 public static Result analyze(Context c,Uri u,long dur){MediaMetadataRetriever r=new MediaMetadataRetriever();Bitmap prev=null;try{r.setDataSource(c,u);int fps=30;try{String q=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_CAPTURE_FRAMERATE);if(q!=null)fps=Math.max(1,Math.round(Float.parseFloat(q)));}catch(Exception ignored){}int n=Math.max(45,Math.min(121,(int)Math.ceil(dur/1000.0*Math.min(fps,30))+1)),sw=192,sh=108;float[]m=new float[n-1];long[]t=new long[n-1];for(int i=0;i<n;i++){long ms=Math.round(dur*i/(double)(n-1));Bitmap raw=r.getFrameAtTime(ms*1000L,MediaMetadataRetriever.OPTION_CLOSEST);if(raw==null)continue;Bitmap cur=Bitmap.createScaledBitmap(raw,sw,sh,true);if(prev!=null){float sum=0;for(int y=6;y<sh-5;y+=2)for(int x=8;x<sw-7;x+=2){int a=prev.getPixel(x,y),b=cur.getPixel(x,y);int ga=(Color.red(a)*30+Color.green(a)*59+Color.blue(a)*11)/100,gb=(Color.red(b)*30+Color.green(b)*59+Color.blue(b)*11)/100;sum+=Math.abs(gb-ga);}m[i-1]=sum/2500f;t[i-1]=ms;}if(prev!=null)prev.recycle();prev=cur;}int ev=0;for(int i=1;i<m.length;i++)if(m[i]>m[ev])ev=i;return new Result(m,t,fps,ev);}finally{if(prev!=null)prev.recycle();try{r.release();}catch(Exception ignored){}}}
 public static CompareResult compare(Result a,Result b){int n=81;float[]aa=res(a,n),bb=res(b,n);float ma=max(aa),mb=max(bb),sum=0,w=-1;int wi=0;for(int i=0;i<n;i++){float d=Math.abs(aa[i]/ma-bb[i]/mb);sum+=d;if(d>w){w=d;wi=i;}}float sc=Math.min(100,sum/n*125);long am=time(a,wi,n),bm=time(b,wi,n);String lv=sc<18?"정상 범위 후보":sc<35?"주의 후보":"이상 후보";String s=String.format(Locale.getDefault(),"v0.5 고속 동작 · %s\nA FPS≈%d / B FPS≈%d\nEvent 동기화 패턴 편차 %.1f/100\n최대 차이 시점 A %.3fs / B %.3fs\n※ Golden 정상범위 전에는 NG 확정값이 아닙니다. 30fps는 약 33ms보다 짧은 현상을 놓칠 수 있습니다.",lv,a.fps,b.fps,sc,am/1000f,bm/1000f);return new CompareResult(draw(aa,bb,wi,sc),s);}
 private static float[]res(Result r,int n){float[]o=new float[n];int sp=Math.max(8,r.m.length/3);for(int i=0;i<n;i++){float z=r.event-sp+2f*sp*i/(n-1);int p=Math.max(0,Math.min(r.m.length-1,(int)Math.floor(z))),q=Math.min(r.m.length-1,p+1);float f=Math.max(0,Math.min(1,z-p));o[i]=r.m[p]*(1-f)+r.m[q]*f;}return o;} private static long time(Result r,int i,int n){int sp=Math.max(8,r.m.length/3),k=Math.round(r.event-sp+2f*sp*i/(n-1));k=Math.max(0,Math.min(r.t.length-1,k));return r.t[k];} private static float max(float[]v){float m=.001f;for(float z:v)m=Math.max(m,z);return m;}
 private static Bitmap draw(float[]a,float[]b,int wi,float sc){int w=1200,h=700,l=70,rr=1140,t=140,bot=550;Bitmap o=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(o);c.drawColor(Color.WHITE);Paint p=new Paint(1);p.setColor(Color.rgb(15,48,88));p.setTextSize(36);p.setFakeBoldText(true);c.drawText(LanguageManager.ts("v0.5 High-Speed Event Sync"),45,55,p);p.setFakeBoldText(false);p.setTextSize(22);p.setColor(Color.DKGRAY);c.drawText(LanguageManager.ts("Peak Event 자동 동기화 → 최대 차이 후보 표시"),45,92,p);p.setStyle(Paint.Style.STROKE);p.setColor(Color.LTGRAY);c.drawRect(l,t,rr,bot,p);float ma=max(a),mb=max(b);Paint pa=new Paint(1);pa.setStyle(Paint.Style.STROKE);pa.setStrokeWidth(5);pa.setColor(Color.rgb(30,90,210));Paint pb=new Paint(pa);pb.setColor(Color.rgb(220,65,45));for(int i=1;i<a.length;i++){float x1=l+(rr-l)*(i-1f)/(a.length-1),x2=l+(rr-l)*i/(a.length-1);c.drawLine(x1,bot-(bot-t-20)*a[i-1]/ma,x2,bot-(bot-t-20)*a[i]/ma,pa);c.drawLine(x1,bot-(bot-t-20)*b[i-1]/mb,x2,bot-(bot-t-20)*b[i]/mb,pb);}float wx=l+(rr-l)*wi/(a.length-1f);p.setColor(Color.MAGENTA);p.setStrokeWidth(7);c.drawLine(wx,t,wx,bot,p);p.setStyle(Paint.Style.FILL);p.setTextSize(26);p.setColor(Color.DKGRAY);c.drawText(String.format(Locale.getDefault(),"Pattern deviation %.1f / 100",sc),75,625,p);return o;}
}
