package com.example.electrodecutcompare;

import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;
import java.io.*;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;

/** Field-first measured dashboard and deliberate, user-confirmed Android share sheet. */
public final class MotionReviewActivity extends Activity {
 private Uri aUri,bUri;private String profile;private boolean busy;private int maxFps;private MotionCore.Comparison result;
 private LinearLayout root,results;private TextView state;private ProgressBar bar;private Button start,regionA,regionB,share;
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final AtomicBoolean cancel=new AtomicBoolean();private double elapsed;
 private MotionRegionStore.Settings settingsA,settingsB;private ReviewReport.Bundle report;private long started;
 private String inspectedAt="";
 private static String f(String a,String b,String c,String d){return ReviewText.of(a,b,c,d);}
 @Override public void onCreate(Bundle state){super.onCreate(state);LanguageManager.init(this);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(true);
  String ua=getIntent().getStringExtra("uriA"),ub=getIntent().getStringExtra("uriB");if(ua==null||ub==null){finish();return;}aUri=Uri.parse(ua);bUri=Uri.parse(ub);profile=getIntent().getStringExtra("profile");if(profile==null)profile="45° Cutter";maxFps=getIntent().getIntExtra("maxFps",30);build();
 }
 private void build(){
  ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(ReviewUi.BG);scroll.setFillViewport(true);root=ReviewUi.column(this);scroll.addView(root);setContentView(scroll);
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=ReviewUi.title(this,ReviewText.title()+"\nv2.0.0");head.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button language=ReviewUi.button(this,LanguageManager.flag());head.addView(language,new LinearLayout.LayoutParams(ReviewUi.dp(this,58),ReviewUi.dp(this,52)));language.setOnClickListener(v->{if(busy)return;new AlertDialog.Builder(this).setItems(new String[]{"🇰🇷 한국어","🇬🇧 English","🇵🇱 Polski","🇺🇦 Українська"},(d,i)->{LanguageManager.setLanguage(this,new String[]{"ko","en","pl","uk"}[i]);report=null;build();if(result!=null)showResult();}).show();});root.addView(head);
  root.addView(ReviewUi.text(this,f("실제 추적 → 측정 가능 여부 → 차이 확인 → 결과 공유","Track → validate measurement → compare → share","Śledź → sprawdź pomiar → porównaj → udostępnij","Відстежте → перевірте вимірювання → порівняйте → поділіться"),17,ReviewUi.MUTED));
  regionA=ReviewUi.button(this,f("① A 커터 / 고정부 지정","① A target / fixed regions","① Obszary celu / ramy A","① Ділянки цілі / рами A"));regionB=ReviewUi.button(this,f("② B 커터 / 고정부 지정","② B target / fixed regions","② Obszary celu / ramy B","② Ділянки цілі / рами B"));root.addView(regionA);root.addView(regionB);regionA.setOnClickListener(v->regions(aUri,"A"));regionB.setOnClickListener(v->regions(bUri,"B"));
  settingsA=MotionRegionStore.get(this,aUri.toString(),profile);settingsB=MotionRegionStore.get(this,bUri.toString(),profile);
  String setup=f("지정 완료","Ready","Gotowe","Готово");if(settingsA.complete())regionA.append(" ✓ "+setup);if(settingsB.complete())regionB.append(" ✓ "+setup);
  Button help=ReviewUi.button(this,f("ⓘ 측정 / 공유 사용방법","ⓘ Measurement / sharing guide","ⓘ Pomiar / udostępnianie — instrukcja","ⓘ Інструкція вимірювання / поширення"));root.addView(help);help.setOnClickListener(v->{if(!busy)startActivity(new Intent(this,GuideActivity.class));});
  start=ReviewUi.button(this,f("▶ 측정형 통합검사 시작","▶ Start measured inspection","▶ Uruchom kontrolę pomiarową","▶ Почати вимірювальну перевірку"));root.addView(start);start.setOnClickListener(v->run());
  bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);root.addView(bar,new LinearLayout.LayoutParams(-1,ReviewUi.dp(this,14)));
  state=ReviewUi.text(this,f("부위를 지정하고 시작하세요. 이 모드는 이전 점수를 사용하지 않습니다.","Select regions and start. This mode does not reuse the previous scores.","Wybierz obszary i uruchom. Ten tryb nie używa poprzednich punktacji.","Виберіть ділянки та почніть. Цей режим не використовує попередні бали."),17,ReviewUi.MUTED);root.addView(state);
  results=ReviewUi.column(this);root.addView(results);
  share=ReviewUi.button(this,f("↗ 결과 내보내기 · 카톡 / 메일","↗ Export results · chat / email","↗ Eksport wyników · czat / e-mail","↗ Експорт результатів · чат / пошта"));share.setEnabled(result!=null);root.addView(share);share.setOnClickListener(v->metadata());
  Button history=ReviewUi.button(this,f("이전 내보내기 이력","Previous exports","Poprzednie eksporty","Попередні експорти"));root.addView(history);history.setOnClickListener(v->history());
  root.addView(ReviewUi.text(this,ReviewText.caveat(),15,ReviewUi.WARN));
 }
 private void regions(Uri u,String role){if(busy)return;Intent i=new Intent(this,MotionRegionActivity.class);i.putExtra("uri",u.toString());i.putExtra("profile",profile);i.putExtra("role",role);startActivityForResult(i,11);}
 @Override protected void onActivityResult(int request,int code,Intent data){super.onActivityResult(request,code,data);if(request==11&&code==RESULT_OK){result=null;report=null;build();}}
 private void lock(boolean value){busy=value;start.setEnabled(!value);regionA.setEnabled(!value);regionB.setEnabled(!value);share.setEnabled(!value&&result!=null);}
 private void run(){
  if(busy)return;settingsA=MotionRegionStore.get(this,aUri.toString(),profile);settingsB=MotionRegionStore.get(this,bUri.toString(),profile);
  if(!settingsA.complete()||!settingsB.complete()){ReviewUi.error(this,f("A와 B에서 커터 1곳, 고정부 2곳을 먼저 지정해주세요.","First select one cutter and two fixed regions in both A and B.","Najpierw wskaż nóż i dwa punkty ramy w obu filmach A i B.","Спершу позначте різак і дві точки рами в обох відео A та B."));return;}
  result=null;report=null;results.removeAllViews();bar.setProgress(0);cancel.set(false);lock(true);started=android.os.SystemClock.elapsedRealtime();inspectedAt=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss Z",Locale.ROOT).format(new Date());
  state.setText(f("A 추적 중 · 취소는 뒤로가기","Tracking A · Back cancels","Śledzenie A · Wstecz anuluje","Відстеження A · Назад скасовує"));
  worker.execute(()->{try{
   MotionCore.Analysis a=MotionReviewEngine.run(this,aUri,settingsA,maxFps,cancel,p->progress(p/2,"A"));
   MotionCore.Analysis b=MotionReviewEngine.run(this,bUri,settingsB,maxFps,cancel,p->progress(50+p/2,"B"));a.role="A";b.role="B";
   MotionCore.Comparison compared=MotionCore.compare(a,b);double seconds=(android.os.SystemClock.elapsedRealtime()-started)/1000.0;
   runOnUiThread(()->{if(isFinishing())return;result=compared;elapsed=seconds;bar.setProgress(100);lock(false);showResult();});
  }catch(Exception e){runOnUiThread(()->{if(isFinishing())return;lock(false);bar.setProgress(0);state.setText(f("분석 완료 아님 · ","Analysis not completed · ","Analiza nieukończona · ","Аналіз не завершено · ")+friendly(e));});}});
 }
 private void progress(int percent,String side){runOnUiThread(()->{if(isFinishing())return;bar.setProgress(percent);state.setText(side+" · "+percent+"% · "+f("실제 프레임 시간으로 추적","Tracking with actual frame timestamps","Śledzenie z rzeczywistymi znacznikami czasu","Відстеження за фактичними мітками часу"));});}
 private String friendly(Exception e){String m=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();if(m.contains("YUV"))return f("이 영상/기기에서 CPU 프레임을 읽지 못했습니다. H.264 표준 영상으로 다시 선택하세요. 결과를 임의 생성하지 않았습니다.","Cannot decode CPU frames for this clip/device. Try a standard H.264 video. No results were fabricated.","Nie można odczytać klatek na tym urządzeniu. Spróbuj standardowego H.264. Wyniki nie zostały wygenerowane sztucznie.","Не вдалося прочитати кадри на цьому пристрої. Спробуйте стандартне H.264. Результати не вигадано.");if(m.contains("LOW_TEXTURE"))return f("무늬가 부족합니다. 커터/고정부의 볼트나 각진 무늬로 영역을 다시 지정하세요.","Too little texture. Select a bolt or textured feature on the cutter/fixed frame.","Za mało tekstury. Wybierz śrubę lub wyraźny detal noża/ramy.","Замало текстури. Виберіть болт або чітку деталь різака/рами.");if(m.contains("REFERENCES_TOO_CLOSE"))return f("고정부 2곳을 더 멀리 떨어뜨려 지정하세요.","Place the two fixed references farther apart.","Wskaż dwa stałe punkty dalej od siebie.","Позначте дві нерухомі точки далі одна від одної.");return m;}
 private void showResult(){
  if(result==null)return;results.removeAllViews();state.setText(String.format(Locale.ROOT,"%.1fs · ",elapsed)+f("분석 완료 · 측정 상태를 먼저 확인하세요","Analysis finished · check measurement status first","Analiza zakończona · najpierw sprawdź stan pomiaru","Аналіз завершено · спершу перевірте стан вимірювання"));
  LinearLayout quality=ReviewUi.card(this);quality.addView(ReviewUi.title(this,f("측정 상태 ≠ 설비 품질 판정","Measurement status ≠ quality verdict","Stan pomiaru ≠ ocena jakości","Стан вимірювання ≠ оцінка якості")));
  quality.addView(ReviewUi.text(this,"A · "+ReviewText.reason(result.a.qualityReason)+"\nB · "+ReviewText.reason(result.b.qualityReason),18,(!result.a.usable||!result.b.usable)?ReviewUi.WARN:ReviewUi.WHITE));quality.addView(ReviewUi.text(this,ReviewText.basis(result.usingA),16,ReviewUi.WARN));results.addView(quality);
  if(result.a.truncated||result.b.truncated)results.addView(ReviewUi.text(this,f("앞부분 최대 30초만 분석했습니다. 전체 영상 결과가 아닙니다.","At most the first 30 seconds were analyzed, not the entire video.","Przeanalizowano najwyżej pierwsze 30 sekund, nie cały film.","Проаналізовано щонайбільше перші 30 секунд, не все відео."),17,ReviewUi.WARN));
  LinearLayout table=ReviewUi.card(this);table.addView(ReviewUi.title(this,f("핵심 측정값","Key measurements","Kluczowe pomiary","Ключові вимірювання")));for(String[] row:ReviewReport.metricRows(result)){table.addView(ReviewUi.text(this,row[0],15,ReviewUi.MUTED));TextView val=ReviewUi.text(this,row[1],23,ReviewUi.WHITE);val.setTypeface(null,Typeface.BOLD);table.addView(val);}results.addView(table);
  if(result.a.cycles.size()>0||result.b.cycles.size()>0){ReviewChart shape=new ReviewChart(this,result,false),time=new ReviewChart(this,result,true);results.addView(shape,new LinearLayout.LayoutParams(-1,ReviewUi.dp(this,245)));results.addView(time,new LinearLayout.LayoutParams(-1,ReviewUi.dp(this,245)));}
  results.addView(ReviewUi.title(this,f("차이 후보 TOP3 · 형태 편차 순","TOP3 difference candidates · ranked by shape","TOP3 różnic · według odchylenia kształtu","TOP3 кандидатів відмінностей · за формою")));
  if(result.ranked.isEmpty())results.addView(ReviewUi.text(this,f("측정 조건 미충족 · 차이 순위를 만들지 않습니다.","Measurement checks failed · no ranking generated.","Warunki pomiaru niespełnione · bez rankingu.","Умови вимірювання не виконано · рейтинг не створено."),18,ReviewUi.WARN));
  for(int i=0;i<Math.min(3,result.ranked.size());i++){MotionCore.Cycle cy=result.ranked.get(i);final int rank=i;LinearLayout card=ReviewUi.card(this);card.addView(ReviewUi.title(this,"TOP "+(i+1)+" · B Cycle "+cy.id));card.addView(ReviewUi.text(this,ReviewText.phase(cy.rankPhase)+" · "+ReviewReport.num(cy.maxPhase*100)+"%",20,ReviewUi.WARN));card.addView(ReviewUi.text(this,f("형태 차이 ","Shape difference ","Różnica kształtu ","Різниця форми ")+ReviewReport.num(cy.shapeDiff)+"% RMS\n"+f("사이클 시간 변화 ","Cycle duration change ","Zmiana czasu cyklu ","Зміна часу циклу ")+ReviewReport.num(cy.timeDeltaPct)+"%",18,ReviewUi.WHITE));
   Button replay=ReviewUi.button(this,f("▶ 기준 회차와 비교재생","▶ Replay against reference cycle","▶ Odtwórz z cyklem odniesienia","▶ Відтворити з еталонним циклом"));card.addView(replay);replay.setOnClickListener(v->replay(rank));results.addView(card);}
  results.addView(ReviewUi.text(this,f("최대 차이가 있는 위상으로 동작명을 추정합니다. ‘커팅/충격’은 임의로 붙이지 않습니다. 색은 차이 후보 표시이며 품질 NG가 아닙니다.","Motion phases follow the measured trajectory. Cutting/impact is not assigned automatically. Colors highlight differences, not quality NG.","Fazy wynikają z pomiaru trajektorii. Cięcie/udar nie są przypisywane automatycznie. Kolory nie oznaczają jakości NG.","Фази визначено за виміряною траєкторією. Різання/удар не призначаються автоматично. Кольори не означають якість NG."),15,ReviewUi.MUTED));share.setEnabled(true);
 }
 private void replay(int rank){MotionCore.Cycle b=result.ranked.get(rank);MotionCore.Analysis left=result.usingA?result.a:result.b;MotionCore.Cycle a=MotionCore.representative(left);if(a==null)return;Intent i=new Intent(this,CycleReplayActivity.class);i.putExtra("uriA",(result.usingA?aUri:bUri).toString());i.putExtra("uriB",bUri.toString());i.putExtra("aStart",(float)left.time[a.start]);i.putExtra("aEnd",(float)left.time[a.end]);i.putExtra("bStart",(float)result.b.time[b.start]);i.putExtra("bEnd",(float)result.b.time[b.end]);i.putExtra("aCycle",a.id);i.putExtra("bCycle",b.id);i.putExtra("rank",rank+1);i.putExtra("stage",ReviewText.phase(b.rankPhase));i.putExtra("stageIndex",b.rankPhase);i.putExtra("deviation",(float)b.shapeDiff);i.putExtra("reviewed",true);i.putExtra("leftLabel",result.usingA?"A":"B median");i.putExtra("problemStart",(float)Math.max(0,b.maxPhase-.06));i.putExtra("problemEnd",(float)Math.min(1,b.maxPhase+.06));startActivity(i);}
 private void metadata(){if(result==null||busy)return;if(report!=null){shareMenu(report);return;}LinearLayout form=ReviewUi.column(this);String[] labels={f("라인","Line","Linia","Лінія"),f("설비 A / B","Equipment A / B","Maszyny A / B","Обладнання A / B"),f("점검자","Inspector","Kontroler","Інспектор")};EditText[] inputs=new EditText[3];android.content.SharedPreferences prefs=getSharedPreferences("report_meta_v200",0);for(int i=0;i<3;i++){inputs[i]=new EditText(this);inputs[i].setHint(labels[i]);inputs[i].setText(prefs.getString("v"+i,""));form.addView(inputs[i]);}
  new AlertDialog.Builder(this).setTitle(f("보고서 정보","Report details","Dane raportu","Дані звіту")).setView(form).setNegativeButton(f("취소","Cancel","Anuluj","Скасувати"),null).setPositiveButton(f("보고서 생성","Create report","Utwórz raport","Створити звіт"),(d,w)->{ReviewReport.Meta m=new ReviewReport.Meta();String[] values=new String[3];for(int i=0;i<3;i++){values[i]=inputs[i].getText().toString().trim();prefs.edit().putString("v"+i,values[i]).apply();}m.line=values[0];m.equipment=values[1];m.operator=values[2];m.profile=profile;m.date=inspectedAt;m.elapsed=elapsed;lock(true);state.setText(f("요약 + 전체 측정 + A/B 합성 이미지 + Excel 생성 중","Creating overview, all measurements, A/B composites and Excel","Tworzenie podsumowania, pomiarów, obrazów A/B i Excel","Створення підсумку, вимірювань, зображень A/B та Excel"));worker.execute(()->{try{ReviewReport.Bundle ready=new ReviewReport(this,result,aUri,bUri,settingsA,settingsB,m).create();runOnUiThread(()->{if(isFinishing())return;report=ready;lock(false);state.setText(f("보고서 생성 완료 · 전송 전 미리보기 가능","Report ready · preview before sharing","Raport gotowy · podgląd przed wysłaniem","Звіт готовий · перегляд перед надсиланням"));shareMenu(ready);});}catch(Exception e){runOnUiThread(()->{if(isFinishing())return;lock(false);ReviewUi.error(this,friendly(e));});}});}).show();
 }
 private void shareMenu(ReviewReport.Bundle bundle){new AlertDialog.Builder(this).setTitle(f("내보내기","Export","Eksport","Експорт")).setItems(new String[]{f("① 요약 이미지 미리보기","① Preview overview image","① Podgląd podsumowania","① Перегляд підсумку"),f("② 이미지 공유 · 카톡/메일 (10장씩)","② Share images · chat/email (10 per batch)","② Udostępnij obrazy · czat/e-mail (po 10)","② Поділитися зображеннями · чат/пошта (по 10)"),f("③ Excel(.xlsx) 공유","③ Share Excel (.xlsx)","③ Udostępnij Excel (.xlsx)","③ Поділитися Excel (.xlsx)"),f("④ 전체 ZIP 공유 · 메일","④ Share full ZIP · email","④ Udostępnij ZIP · e-mail","④ Поділитися ZIP · пошта")},(d,i)->{if(i==0&&!bundle.images.isEmpty()){Intent v=new Intent(this,ZoomImageActivity.class);v.putExtra("path",bundle.images.get(0).getPath());startActivity(v);}else if(i==1)imageBatches(bundle);else if(i==2)send(Collections.singletonList(bundle.xlsx),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");else if(i==3)send(Collections.singletonList(bundle.zip),"application/zip");}).show();}
 private void imageBatches(ReviewReport.Bundle b){int n=(b.images.size()+9)/10;String[] labels=new String[n];for(int i=0;i<n;i++)labels[i]=f("이미지 ","Images ","Obrazy ","Зображення ")+(i*10+1)+"–"+Math.min(b.images.size(),i*10+10)+" / "+b.images.size();new AlertDialog.Builder(this).setTitle(f("보낼 묶음을 선택하세요","Choose a batch to share","Wybierz partię do wysłania","Виберіть пакет для надсилання")).setItems(labels,(dialog,i)->send(b.images.subList(i*10,Math.min(b.images.size(),i*10+10)),"image/jpeg")).show();}
 private void send(List<File> files,String mime){try{ArrayList<Uri> uris=new ArrayList<>();for(File file:files)uris.add(ReportShareProvider.uri(this,file));if(uris.isEmpty())return;Intent s=new Intent(uris.size()==1?Intent.ACTION_SEND:Intent.ACTION_SEND_MULTIPLE);s.setType(mime);s.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);if(uris.size()==1)s.putExtra(Intent.EXTRA_STREAM,uris.get(0));else s.putParcelableArrayListExtra(Intent.EXTRA_STREAM,uris);ClipData clip=ClipData.newUri(getContentResolver(),"Cutter report",uris.get(0));for(int j=1;j<uris.size();j++)clip.addItem(new ClipData.Item(uris.get(j)));s.setClipData(clip);s.putExtra(Intent.EXTRA_SUBJECT,"Lami Cutter Inspection");startActivity(Intent.createChooser(s,f("전송 앱과 수신자를 직접 선택하세요","Choose app and recipient","Wybierz aplikację i odbiorcę","Виберіть застосунок і одержувача")));}catch(Exception e){ReviewUi.error(this,friendly(e));}}
 private void history(){File dir=new File(getFilesDir(),"reports");File[] folders=dir.listFiles(File::isDirectory);if(folders==null||folders.length==0){ReviewUi.error(this,f("내보내기 이력이 없습니다.","No previous exports.","Brak poprzednich eksportów.","Немає попередніх експортів."));return;}Arrays.sort(folders,(a,b)->b.getName().compareTo(a.getName()));String[] names=new String[folders.length];for(int i=0;i<names.length;i++)names[i]=folders[i].getName();new AlertDialog.Builder(this).setTitle(f("저장된 보고서","Saved reports","Zapisane raporty","Збережені звіти")).setItems(names,(d,i)->{ReviewReport.Bundle b=new ReviewReport.Bundle();b.dir=folders[i];File[] files=b.dir.listFiles();if(files!=null){Arrays.sort(files,Comparator.comparing(File::getName));for(File q:files){if(q.getName().endsWith(".jpg"))b.images.add(q);if(q.getName().endsWith(".xlsx"))b.xlsx=q;if(q.getName().endsWith(".zip"))b.zip=q;}}if(b.xlsx!=null&&b.zip!=null)shareMenu(b);}).show();}
 @Override public void onBackPressed(){if(busy){new AlertDialog.Builder(this).setMessage(f("작업을 취소하고 나갈까요?","Cancel and leave?","Anulować i wyjść?","Скасувати та вийти?")).setNegativeButton(f("계속","Continue","Kontynuuj","Продовжити"),null).setPositiveButton("OK",(d,w)->{cancel.set(true);worker.shutdownNow();finish();}).show();}else super.onBackPressed();}
 @Override protected void onDestroy(){cancel.set(true);worker.shutdownNow();super.onDestroy();}
}
