package com.example.electrodecutcompare;
import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.zip.*;
/** Minimal genuine OOXML workbook; user text is always inlineStr, never an executable formula. */
public final class ReviewXlsx {
 public static final class Sheet {public String name;public final List<List<Object>> rows=new ArrayList<>();public Sheet(String n){name=n;}public Sheet row(Object... v){rows.add(Arrays.asList(v));return this;}}
 private static String xml(String s){StringBuilder b=new StringBuilder();for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c<32&&c!='\n'&&c!='\r'&&c!='\t')continue;switch(c){case '&':b.append("&amp;");break;case '<':b.append("&lt;");break;case '>':b.append("&gt;");break;case '"':b.append("&quot;");break;default:b.append(c);}}return b.toString();}
 private static void entry(ZipOutputStream z,String name,String text)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(text.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
 private static String col(int i){String s="";for(int n=i+1;n>0;n=(n-1)/26)s=(char)('A'+(n-1)%26)+s;return s;}
 public static void write(File f,List<Sheet> sheets)throws IOException{
  try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(f))){
   String ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";String rel="http://schemas.openxmlformats.org/officeDocument/2006/relationships";
   StringBuilder ct=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>");
   StringBuilder wb=new StringBuilder("<workbook xmlns=\""+ns+"\" xmlns:r=\""+rel+"\"><sheets>");StringBuilder rs=new StringBuilder("<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">");
   for(int i=0;i<sheets.size();i++){int id=i+1;Sheet s=sheets.get(i);String name=s.name.replaceAll("[\\\\/?*\\[\\]:]","_");if(name.length()>31)name=name.substring(0,31);
    wb.append("<sheet name=\"").append(xml(name)).append("\" sheetId=\"").append(id).append("\" r:id=\"rId").append(id).append("\"/>");rs.append("<Relationship Id=\"rId").append(id).append("\" Type=\"").append(rel).append("/worksheet\" Target=\"worksheets/sheet").append(id).append(".xml\"/>");ct.append("<Override PartName=\"/xl/worksheets/sheet").append(id).append(".xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>");
    StringBuilder x=new StringBuilder("<worksheet xmlns=\""+ns+"\"><sheetViews><sheetView workbookViewId=\"0\"><pane ySplit=\"1\" topLeftCell=\"A2\" activePane=\"bottomLeft\" state=\"frozen\"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight=\"30\"/><cols><col min=\"1\" max=\"30\" width=\"23\" customWidth=\"1\"/></cols><sheetData>");
    int ri=0,maxCol=1;for(List<Object> row:s.rows){ri++;maxCol=Math.max(maxCol,row.size());x.append("<row r=\"").append(ri).append("\" ht=\"").append(ri==1?40:32).append("\" customHeight=\"1\">");for(int ci=0;ci<row.size();ci++){Object val=row.get(ci);String cell=col(ci)+ri;boolean numeric=val instanceof Number && Double.isFinite(((Number)val).doubleValue());int style=ri==1?1:numeric?(val instanceof Integer||val instanceof Long?3:2):0;x.append("<c r=\"").append(cell).append("\" s=\"").append(style).append("\"");if(numeric)x.append("><v>").append(val).append("</v></c>");else x.append(" t=\"inlineStr\"><is><t xml:space=\"preserve\">").append(xml(val==null?"":val.toString())).append("</t></is></c>");}x.append("</row>");}x.append("</sheetData>");if(ri>1)x.append("<autoFilter ref=\"A1:").append(col(maxCol-1)).append(ri).append("\"/>");x.append("</worksheet>");entry(z,"xl/worksheets/sheet"+id+".xml",x.toString());
   }
   wb.append("</sheets></workbook>");rs.append("<Relationship Id=\"styles\" Type=\"").append(rel).append("/styles\" Target=\"styles.xml\"/></Relationships>");ct.append("</Types>");entry(z,"[Content_Types].xml",ct.toString());entry(z,"xl/workbook.xml",wb.toString());entry(z,"xl/_rels/workbook.xml.rels",rs.toString());entry(z,"_rels/.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\""+rel+"/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
   entry(z,"xl/styles.xml","<styleSheet xmlns=\""+ns+"\"><numFmts count=\"1\"><numFmt numFmtId=\"164\" formatCode=\"0.000000\"/></numFmts><fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font><font><b/><sz val=\"11\"/><color rgb=\"FFFFFFFF\"/><name val=\"Calibri\"/></font></fonts><fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF123C5C\"/><bgColor indexed=\"64\"/></patternFill></fill></fills><borders count=\"1\"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"4\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyAlignment=\"1\"><alignment wrapText=\"1\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"1\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyAlignment=\"1\"><alignment wrapText=\"1\" vertical=\"center\"/></xf><xf numFmtId=\"164\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"1\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/></cellXfs><cellStyles count=\"1\"><cellStyle name=\"Normal\" xfId=\"0\" builtinId=\"0\"/></cellStyles></styleSheet>");
  }
 }
}
